### PR TITLE
Allow transformers-6.0

### PR DESCRIPTION
**Pull request by matobet**

### CODE REVIEW

**Comment by phadej** [comment]
Please read through https://github.com/phadej/insert-ordered-containers/blob/master/CONTRIBUTING.md

I also won't support `transformers-0.6` before GHC bundles them. It's just a PITA testing wise. CI doesn't pick that version. Until then use `allow-newer`.

**Comment by ysangkok** [comment]
The merge into GHC is blocked by judah/haskeline#173

**Comment by ysangkok** [comment]
@phadej GHC now bundles transformers-0.6: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9370

**Comment by ysangkok** [comment]
@phadej What about now :) ? Would appreciate it.

**Comment by ysangkok** [comment]
@matobet haskell-ci-0.16 supports GHC 9.6, so it would be nice if this PR included CI.

**Pull request closed without merging**
